branch-defaults:
  main:
    environment: coffee-shop-production
    group_suffix: null
environment-defaults:
  coffee-shop-production:
    branch: null
    repository: null
global:
  application_name: Django_Platzi_Project
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
